# Generated by Django 3.2.13 on 2022-05-07 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizzas', '0003_auto_20220505_1752'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='topping',
            options={'verbose_name_plural': 'Toppings'},
        ),
    ]
